exception CannotPrintType
exception DuplicateFunctionName of string
exception DuplicateVariable of string
exception FunctionNameReserved 
exception FunctionNotDefined of string
exception IncorrectArgumentType of string
exception InvalidBinaryOperation
exception InvalidExecFormat of string 
exception InvalidIfStatementType
exception InvalidUnaryOperation
exception MalformedTokens
exception NothingAfterReturn
exception SyntaxError of string
exception UndefinedId of string
exception WrongNumberOfArguments
