exception CannotPrintType
exception DuplicateFunctionName of string
exception DuplicateVariable of string
exception FunctionNameReserved 
exception FunctionNotDefined of string
exception IncorrectArgumentType of string
exception InvalidBinaryOperation
exception InvalidIfStatementType
exception InvalidUnaryOperation
exception NothingAfterReturn
exception UndefinedId of string
exception WrongNumberOfArguments
