exception CannotPrintType
exception DuplicateFunctionName of string
exception DuplicateVariable of string
exception FunctionNameReserved 
exception FunctionNotDefined of string
exception IncorrectArgumentType of string
exception IndexError
exception InvalidBinaryOperation
exception InvalidCondition
exception InvalidExecFormat of string 
exception InvalidIfStatementType
exception InvalidListAssignmentOperation 
exception InvalidListElementType
exception InvalidSliceOperation 
exception InvalidUnaryOperation
exception ListElementsOfVariantType
exception MalformedTokens
exception NothingAfterReturn
exception SyntaxError of string
exception TypeMismatch of string
exception UndefinedId of string
exception WrongNumberOfArguments
